---
- name: Update and upgrade apt packages
  hosts: all 
  tasks:
    - name: Update packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: '*'
        state: latest

    - name: Upgrade packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: '*'
        state: latest
        exclude: kernel*
